# Generated by Django 6.0.6 on 2026-07-18 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petcosmetic',
            name='is_equipped',
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='coin_cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='img_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
